version: "3.7"

services:
  maria:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_DATABASE=wordpress
    networks:
      - dev
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:5.8-php8.0-apache
    volumes:
      #- ./:/var/www/html/wp-content/plugins/coding-challenge
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
    depends_on:
      - maria
    ports:
      - 8888:80
    environment:
      - WORDPRESS_DB_HOST=maria
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=false
    networks:
      - dev

volumes:
  db:

networks:
  dev:
